framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
        excluded_patterns: 
            - 'vendor/easycorp/easyadmin-bundle/src/Resources/public/**/*'

sensiolabs_typescript:
    source_dir: ['%kernel.project_dir%/assets/typescript']
