framework:
  mailer:
    dsn: "%env(MAILER_DSN)%"
    envelope:
      sender: "%app_contact_email%"
    headers:
      From: "%app_name% <%app_contact_email%>"
      X-Auto-Response-Suppress: "OOF, DR, RN, NRN, AutoReply"
