framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: '%env(APP_CONTACT_EMAIL)%'
        headers:
            From: '%env(APP_NAME)% <%env(APP_CONTACT_EMAIL)%>'
            X-Auto-Response-Suppress: 'OOF, DR, RN, NRN, AutoReply'