twig:
  file_name_pattern: "*.twig"
  globals:
    app_name: !php/const App\Config\AppConfig::APP_NAME
    app_author: !php/const App\Config\AppConfig::APP_AUTHOR
    app_contact_email: !php/const App\Config\AppConfig::APP_CONTACT_EMAIL
  paths:
    "%kernel.project_dir%/assets/styles": styles

when@test:
  twig:
    strict_variables: true
