import {
  AccessibilityHelp,
  Alignment,
  AutoImage,
  AutoLink,
  BalloonToolbar,
  BlockQuote,
  Bold,
  Code,
  CodeBlock,
  Essentials,
  FindAndReplace,
  FontBackgroundColor,
  FontColor,
  FontFamily,
  FontSize,
  FullPage,
  GeneralHtmlSupport,
  Heading,
  Highlight,
  HorizontalLine,
  HtmlComment,
  HtmlEmbed,
  ImageBlock,
  ImageCaption,
  ImageInline,
  ImageInsert,
  ImageInsertViaUrl,
  ImageResize,
  ImageStyle,
  ImageTextAlternative,
  ImageToolbar,
  ImageUpload,
  Indent,
  IndentBlock,
  Italic,
  Link,
  LinkImage,
  List,
  ListProperties,
  MediaEmbed,
  MediaEmbedToolbar,
  Mention,
  Paragraph,
  PasteFromOffice,
  RemoveFormat,
  SelectAll,
  ShowBlocks,
  SimpleUploadAdapter,
  SourceEditing,
  SpecialCharacters,
  SpecialCharactersArrows,
  SpecialCharactersCurrency,
  SpecialCharactersEssentials,
  SpecialCharactersLatin,
  SpecialCharactersMathematical,
  SpecialCharactersText,
  Strikethrough,
  Style,
  Table,
  TableCaption,
  TableCellProperties,
  TableColumnResize,
  TableProperties,
  TableToolbar,
  TextPartLanguage,
  TextTransformation,
  TodoList,
  Underline,
  WordCount,
  // @ts-ignore
} from "ckeditor5";
import EditorWordCounter from "../EditorWordCounter.ts";
import FeatureRichConfigType from "../interface/FeatureRichConfigType.ts";
// @ts-ignore
import frTranslations from "ckeditor5/translations/fr.js";
import {
  trans,
  PLACEHOLDER,
  PLUGIN_LANGUAGE_FRENCH,
  PLUGIN_LANGUAGE_ENGLISH,
  PLUGIN_STYLE_CATEGORY,
  PLUGIN_STYLE_TITLE,
  PLUGIN_STYLE_SUBTITLE,
  PLUGIN_STYLE_CODE_BRIGHT,
  PLUGIN_STYLE_CODE_DARK,
  PLUGIN_STYLE_INFO_BOX,
  PLUGIN_STYLE_SIDE_QUOTE,
  PLUGIN_STYLE_MARKER,
  PLUGIN_STYLE_SPOILER,
} from "../../translator.ts";

export default class EditorFeatureRichConfig {
  private postUuid: string | undefined;
  private editorWordCounter: EditorWordCounter;
  private isDefaultLocale: boolean;

  constructor(
    editorDataset: DOMStringMap,
    editorWordCounter: EditorWordCounter
  ) {
    this.postUuid = editorDataset.postUuid;
    this.editorWordCounter = editorWordCounter;
    this.isDefaultLocale = document.documentElement.lang === "fr";
  }

  public getConfig(): FeatureRichConfigType {
    return {
      fontFamily: {
        supportAllValues: true,
      },
      fontSize: {
        options: [10, 12, 14, "default", 18, 20, 22],
        supportAllValues: true,
      },
      heading: {
        options: [
          {
            model: "paragraph",
            view: "p",
            title: "Paragraph",
            class: "ck-heading_paragraph",
          },
          {
            model: "heading1",
            view: "h1",
            title: "Heading 1",
            class: "ck-heading_heading1",
          },
          {
            model: "heading2",
            view: "h2",
            title: "Heading 2",
            class: "ck-heading_heading2",
          },
          {
            model: "heading3",
            view: "h3",
            title: "Heading 3",
            class: "ck-heading_heading3",
          },
          {
            model: "heading4",
            view: "h4",
            title: "Heading 4",
            class: "ck-heading_heading4",
          },
          {
            model: "heading5",
            view: "h5",
            title: "Heading 5",
            class: "ck-heading_heading5",
          },
          {
            model: "heading6",
            view: "h6",
            title: "Heading 6",
            class: "ck-heading_heading6",
          },
        ],
      },
      htmlSupport: {
        allow: [
          {
            name: /^.*$/,
            styles: true,
            attributes: true,
            classes: true,
          },
        ],
      },
      image: {
        toolbar: [
          "toggleImageCaption",
          "imageTextAlternative",
          "|",
          "imageStyle:wrapText",
          "imageStyle:breakText",
          "|",
          "linkImage",
          "|",
          "resizeImage",
        ],
      },
      language: {
        ui: this.isDefaultLocale ? "fr" : "en",
        content: this.isDefaultLocale ? "fr" : "en",
        textPartLanguage: [
          {
            title: trans(PLUGIN_LANGUAGE_FRENCH, {}, "ckeditor5"),
            languageCode: "fr",
          },
          {
            title: trans(PLUGIN_LANGUAGE_ENGLISH, {}, "ckeditor5"),
            languageCode: "en",
          },
        ],
      },
      licenseKey: "GPL",
      link: {
        addTargetToExternalLinks: true,
        defaultProtocol: "https://",
        decorators: {
          toggleDownloadable: {
            mode: "manual",
            label: "Downloadable",
            attributes: {
              download: "file",
            },
          },
        },
      },
      list: {
        properties: {
          styles: true,
          startIndex: true,
          reversed: true,
        },
      },
      mention: {
        feeds: [
          {
            marker: "@",
            feed: [
              /* See: https://ckeditor.com/docs/ckeditor5/latest/features/mentions.html */
            ],
          },
        ],
      },
      menuBar: {
        isVisible: true,
      },
      placeholder: trans(PLACEHOLDER, {}, "ckeditor5"),
      plugins: [
        AccessibilityHelp,
        Alignment,
        AutoImage,
        AutoLink,
        BalloonToolbar,
        BlockQuote,
        Bold,
        Code,
        CodeBlock,
        Essentials,
        FindAndReplace,
        FontBackgroundColor,
        FontColor,
        FontFamily,
        FontSize,
        FullPage,
        GeneralHtmlSupport,
        Heading,
        Highlight,
        HorizontalLine,
        HtmlComment,
        HtmlEmbed,
        ImageBlock,
        ImageCaption,
        ImageInline,
        ImageInsert,
        ImageInsertViaUrl,
        ImageResize,
        ImageStyle,
        ImageTextAlternative,
        ImageToolbar,
        ImageUpload,
        Indent,
        IndentBlock,
        Italic,
        Link,
        LinkImage,
        List,
        ListProperties,
        MediaEmbed,
        MediaEmbedToolbar,
        Mention,
        Paragraph,
        PasteFromOffice,
        RemoveFormat,
        SelectAll,
        ShowBlocks,
        SimpleUploadAdapter,
        SourceEditing,
        SpecialCharacters,
        SpecialCharactersArrows,
        SpecialCharactersCurrency,
        SpecialCharactersEssentials,
        SpecialCharactersLatin,
        SpecialCharactersMathematical,
        SpecialCharactersText,
        Strikethrough,
        Style,
        Table,
        TableCaption,
        TableCellProperties,
        TableColumnResize,
        TableProperties,
        TableToolbar,
        TextPartLanguage,
        TextTransformation,
        TodoList,
        Underline,
        WordCount,
      ],
      removePlugins: ["MediaEmbedToolbar"],
      simpleUpload: {
        uploadUrl: "/upload-post-image",
        withCredentials: true,
        headers: {
          "X-CSRF-TOKEN": "CSRF-Token",
          Authorization: "Bearer <JSON Web Token>",
          "Post-Uuid": this.postUuid,
        },
      },
      style: {
        definitions: [
          {
            name: trans(PLUGIN_STYLE_TITLE, {}, "ckeditor5"),
            element: "h2",
            classes: ["document-title"],
          },
          {
            name: trans(PLUGIN_STYLE_CATEGORY, {}, "ckeditor5"),
            element: "h3",
            classes: ["category"],
          },
          {
            name: trans(PLUGIN_STYLE_SUBTITLE, {}, "ckeditor5"),
            element: "h3",
            classes: ["document-subtitle"],
          },
          {
            name: trans(PLUGIN_STYLE_CODE_BRIGHT, {}, "ckeditor5"),
            element: "pre",
            classes: ["fancy-code", "fancy-code-bright"],
          },
          {
            name: trans(PLUGIN_STYLE_CODE_DARK, {}, "ckeditor5"),
            element: "pre",
            classes: ["fancy-code", "fancy-code-dark"],
          },
          {
            name: trans(PLUGIN_STYLE_INFO_BOX, {}, "ckeditor5"),
            element: "p",
            classes: ["info-box"],
          },
          {
            name: trans(PLUGIN_STYLE_SIDE_QUOTE, {}, "ckeditor5"),
            element: "blockquote",
            classes: ["side-quote"],
          },
          {
            name: trans(PLUGIN_STYLE_MARKER, {}, "ckeditor5"),
            element: "span",
            classes: ["marker"],
          },
          {
            name: trans(PLUGIN_STYLE_SPOILER, {}, "ckeditor5"),
            element: "span",
            classes: ["spoiler"],
          },
        ],
      },
      table: {
        contentToolbar: [
          "tableColumn",
          "tableRow",
          "mergeTableCells",
          "tableCellProperties",
          "tableProperties",
        ],
      },
      toolbar: {
        items: [
          "undo",
          "redo",
          "|",
          "findAndReplace",
          "selectAll",
          "|",
          "alignment",
          "indent",
          "outdent",
          "|",
          "horizontalLine",
          "|",
          "fontSize",
          "fontFamily",
          "fontColor",
          "fontBackgroundColor",
          "highlight",
          "|",
          "bold",
          "italic",
          "underline",
          "strikethrough",
          "removeFormat",
          "|",
          "specialCharacters",
          "|",
          "bulletedList",
          "numberedList",
          "todoList",
          "|",
          "blockQuote",
          "insertTable",
          "code",
          "codeBlock",
          "|",
          "link",
          "insertImage",
          "mediaEmbed",
          "htmlEmbed",
          "|",
          "heading",
          "|",
          "style",
          "|",
          "textPartLanguage",
          "|",
          "sourceEditing",
          "showBlocks",
          "|",
          "accessibilityHelp",
        ],
        shouldNotGroupWhenFull: true,
      },
      translations: this.isDefaultLocale ? frTranslations : null,
      wordCount: {
        onUpdate: (stats: { characters: number; words: number }) => {
          this.editorWordCounter.updateStats(stats);
        },
      },
    };
  }
}
